package org.course_registration.dao;

import org.course_registration.dataobject.CourseCheckCodeDO;

public interface CourseCheckCodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    int insert(CourseCheckCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    int insertSelective(CourseCheckCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    CourseCheckCodeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    int updateByPrimaryKeySelective(CourseCheckCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    int updateByPrimaryKey(CourseCheckCodeDO record);
}