package org.course_registration.dao;

import org.course_registration.dataobject.StuDO;

public interface StuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int insert(StuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int insertSelective(StuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    StuDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int updateByPrimaryKeySelective(StuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int updateByPrimaryKey(StuDO record);
}