package org.course_registration.dao;

import org.course_registration.dataobject.StuPasswordDO;

public interface StuPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int insert(StuPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int insertSelective(StuPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    StuPasswordDO selectByPrimaryKey(Integer id);

    StuPasswordDO selectByUserId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int updateByPrimaryKeySelective(StuPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    int updateByPrimaryKey(StuPasswordDO record);
}