package org.course_registration.dao;

import org.course_registration.dataobject.StuTransactionDO;
import org.course_registration.dataobject.TchTransactionDO;

import java.util.List;

public interface StuTransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    List<StuTransactionDO> listTransaction(Integer stuId);

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int insert(StuTransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int insertSelective(StuTransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    StuTransactionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int updateByPrimaryKeySelective(StuTransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int updateByPrimaryKey(StuTransactionDO record);
}