package org.course_registration.dao;

import org.course_registration.dataobject.StuWalletDO;

public interface StuWalletDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int insert(StuWalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int insertSelective(StuWalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    StuWalletDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int updateByPrimaryKeySelective(StuWalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int updateByPrimaryKey(StuWalletDO record);
}