package org.course_registration.dao;

import org.course_registration.dataobject.TchDO;

public interface TchDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_info
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_info
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int insert(TchDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_info
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int insertSelective(TchDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_info
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    TchDO selectByPrimaryKey(Integer id);

    TchDO selectByTelephone(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_info
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int updateByPrimaryKeySelective(TchDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_info
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int updateByPrimaryKey(TchDO record);
}