package org.course_registration.dao;

import org.course_registration.dataobject.TchPasswordDO;

public interface TchPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int insert(TchPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int insertSelective(TchPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    TchPasswordDO selectByPrimaryKey(Integer id);

    TchPasswordDO selectByTchId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int updateByPrimaryKeySelective(TchPasswordDO record);

    int updatePasswordByTchId(TchPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    int updateByPrimaryKey(TchPasswordDO record);
}