package org.course_registration.dao;

import org.course_registration.dataobject.TchTransactionDO;

import java.util.List;

public interface TchTransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    List<TchTransactionDO> listTransaction(Integer tchId);

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int insert(TchTransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int insertSelective(TchTransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    TchTransactionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int updateByPrimaryKeySelective(TchTransactionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_transaction
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    int updateByPrimaryKey(TchTransactionDO record);
}