package org.course_registration.dao;

import org.course_registration.dataobject.TchWalletDO;

import java.math.BigDecimal;

public interface TchWalletDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int insert(TchWalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int insertSelective(TchWalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    TchWalletDO selectByPrimaryKey(Integer id);

    TchWalletDO selectByTchId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int updateByPrimaryKeySelective(TchWalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tch_wallet
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    int updateByPrimaryKey(TchWalletDO record);

    void withdrawal(Integer tchId, BigDecimal amount);

    void increaseBalance(Integer tchId, BigDecimal amount);
}