package org.course_registration.dataobject;

public class CourseCheckCodeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_check_code.id
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_check_code.check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    private String checkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_check_code.course_id
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_check_code.id
     *
     * @return the value of course_check_code.id
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_check_code.id
     *
     * @param id the value for course_check_code.id
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_check_code.check_code
     *
     * @return the value of course_check_code.check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    public String getCheckCode() {
        return checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_check_code.check_code
     *
     * @param checkCode the value for course_check_code.check_code
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    public void setCheckCode(String checkCode) {
        this.checkCode = checkCode == null ? null : checkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_check_code.course_id
     *
     * @return the value of course_check_code.course_id
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_check_code.course_id
     *
     * @param courseId the value for course_check_code.course_id
     *
     * @mbg.generated Fri Apr 28 16:30:32 BST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}