package org.course_registration.dataobject;

public class CourseStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_stock.id
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_stock.stock
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_stock.course_id
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_stock.id
     *
     * @return the value of course_stock.id
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_stock.id
     *
     * @param id the value for course_stock.id
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_stock.stock
     *
     * @return the value of course_stock.stock
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_stock.stock
     *
     * @param stock the value for course_stock.stock
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_stock.course_id
     *
     * @return the value of course_stock.course_id
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_stock.course_id
     *
     * @param courseId the value for course_stock.course_id
     *
     * @mbg.generated Mon Apr 24 20:38:55 BST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}