package org.course_registration.dataobject;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.stu_id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.course_id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.price
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.stu_id
     *
     * @return the value of order_info.stu_id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.stu_id
     *
     * @param stuId the value for order_info.stu_id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.course_id
     *
     * @return the value of order_info.course_id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.course_id
     *
     * @param courseId the value for order_info.course_id
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.price
     *
     * @return the value of order_info.price
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.price
     *
     * @param price the value for order_info.price
     *
     * @mbg.generated Fri Jun 09 16:54:24 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}