package org.course_registration.dataobject;

public class StuPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_password.id
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_password.encrypted_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    private String encryptedPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_password.stu_id
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    private Integer stuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_password.id
     *
     * @return the value of stu_password.id
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_password.id
     *
     * @param id the value for stu_password.id
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_password.encrypted_password
     *
     * @return the value of stu_password.encrypted_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    public String getEncryptedPassword() {
        return encryptedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_password.encrypted_password
     *
     * @param encryptedPassword the value for stu_password.encrypted_password
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword == null ? null : encryptedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_password.stu_id
     *
     * @return the value of stu_password.stu_id
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_password.stu_id
     *
     * @param stuId the value for stu_password.stu_id
     *
     * @mbg.generated Fri Apr 21 22:28:05 BST 2023
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
}