package org.course_registration.dataobject;

import java.util.Date;

public class StuTransactionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_transaction.id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_transaction.amount
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_transaction.description
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_transaction.time
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_transaction.stu_id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Integer stuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_transaction.id
     *
     * @return the value of stu_transaction.id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_transaction.id
     *
     * @param id the value for stu_transaction.id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_transaction.amount
     *
     * @return the value of stu_transaction.amount
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_transaction.amount
     *
     * @param amount the value for stu_transaction.amount
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_transaction.description
     *
     * @return the value of stu_transaction.description
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_transaction.description
     *
     * @param description the value for stu_transaction.description
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_transaction.time
     *
     * @return the value of stu_transaction.time
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_transaction.time
     *
     * @param time the value for stu_transaction.time
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_transaction.stu_id
     *
     * @return the value of stu_transaction.stu_id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_transaction.stu_id
     *
     * @param stuId the value for stu_transaction.stu_id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
}