package org.course_registration.dataobject;

public class StuWalletDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_wallet.id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_wallet.balance
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_wallet.stu_id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    private Integer stuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_wallet.id
     *
     * @return the value of stu_wallet.id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_wallet.id
     *
     * @param id the value for stu_wallet.id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_wallet.balance
     *
     * @return the value of stu_wallet.balance
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_wallet.balance
     *
     * @param balance the value for stu_wallet.balance
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_wallet.stu_id
     *
     * @return the value of stu_wallet.stu_id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_wallet.stu_id
     *
     * @param stuId the value for stu_wallet.stu_id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
}