package org.course_registration.dataobject;

public class TchDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_info.id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_info.name
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_info.gender
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_info.telephone
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_info.description
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_info.id
     *
     * @return the value of tch_info.id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_info.id
     *
     * @param id the value for tch_info.id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_info.name
     *
     * @return the value of tch_info.name
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_info.name
     *
     * @param name the value for tch_info.name
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_info.gender
     *
     * @return the value of tch_info.gender
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_info.gender
     *
     * @param gender the value for tch_info.gender
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_info.telephone
     *
     * @return the value of tch_info.telephone
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_info.telephone
     *
     * @param telephone the value for tch_info.telephone
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_info.description
     *
     * @return the value of tch_info.description
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_info.description
     *
     * @param description the value for tch_info.description
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}