package org.course_registration.dataobject;

public class TchPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_password.id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_password.encrypted_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private String encryptedPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_password.tch_id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    private Integer tchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_password.id
     *
     * @return the value of tch_password.id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_password.id
     *
     * @param id the value for tch_password.id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_password.encrypted_password
     *
     * @return the value of tch_password.encrypted_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public String getEncryptedPassword() {
        return encryptedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_password.encrypted_password
     *
     * @param encryptedPassword the value for tch_password.encrypted_password
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword == null ? null : encryptedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_password.tch_id
     *
     * @return the value of tch_password.tch_id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public Integer getTchId() {
        return tchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_password.tch_id
     *
     * @param tchId the value for tch_password.tch_id
     *
     * @mbg.generated Sun Apr 23 20:00:26 BST 2023
     */
    public void setTchId(Integer tchId) {
        this.tchId = tchId;
    }
}