package org.course_registration.dataobject;

import java.util.Date;

public class TchTransactionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_transaction.id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_transaction.amount
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_transaction.description
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_transaction.time
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_transaction.tch_id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    private Integer tchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_transaction.id
     *
     * @return the value of tch_transaction.id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_transaction.id
     *
     * @param id the value for tch_transaction.id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_transaction.amount
     *
     * @return the value of tch_transaction.amount
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_transaction.amount
     *
     * @param amount the value for tch_transaction.amount
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_transaction.description
     *
     * @return the value of tch_transaction.description
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_transaction.description
     *
     * @param description the value for tch_transaction.description
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_transaction.time
     *
     * @return the value of tch_transaction.time
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_transaction.time
     *
     * @param time the value for tch_transaction.time
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_transaction.tch_id
     *
     * @return the value of tch_transaction.tch_id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public Integer getTchId() {
        return tchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_transaction.tch_id
     *
     * @param tchId the value for tch_transaction.tch_id
     *
     * @mbg.generated Sun Jun 04 20:05:34 CST 2023
     */
    public void setTchId(Integer tchId) {
        this.tchId = tchId;
    }
}