package org.course_registration.dataobject;

public class TchWalletDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_wallet.id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_wallet.balance
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tch_wallet.tch_id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    private Integer tchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_wallet.id
     *
     * @return the value of tch_wallet.id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_wallet.id
     *
     * @param id the value for tch_wallet.id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_wallet.balance
     *
     * @return the value of tch_wallet.balance
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_wallet.balance
     *
     * @param balance the value for tch_wallet.balance
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tch_wallet.tch_id
     *
     * @return the value of tch_wallet.tch_id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public Integer getTchId() {
        return tchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tch_wallet.tch_id
     *
     * @param tchId the value for tch_wallet.tch_id
     *
     * @mbg.generated Sun Jun 04 19:16:23 CST 2023
     */
    public void setTchId(Integer tchId) {
        this.tchId = tchId;
    }
}